### ISSUE TITLE
Adding "hint" to the schemas

### ISSUE THREAD

**Issue by Luijinho** [KA226-COVID/APIs#3]
Since we are changing the schemas to support the "visible" property, I think adding the "hint" field to the schemas for the feedback manager would be good. Currently, the feedback manager requests the database only to gather the "hint" for exercises, which is unnecessary, increasing delay to the feedback manager.

**Comment by albsierra** [comment]
I transfer @zpleal the decision on this question.
I will prepare the validators to this possibility to avoid problems if this property is integrated in PEAR schema.

**Comment by zpleal** [comment]
@Luijinho will change PEAR's JSON Schema to handle "visible" as an optional property.
